title: City of Heroes
author: JamesDW
email: jamesdw@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to the City of Heroes page for JamesDW! This is still a work in progress.

# social links
twitter_username: JamesDW
github_username:  JamesDW

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
